# Generated by Django 2.1.7 on 2019-03-26 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardName', models.CharField(max_length=50)),
                ('boardCode', models.CharField(max_length=3)),
                ('boardDesc', models.TextField()),
                ('isActive', models.IntegerField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threadTitle', models.TextField()),
                ('threadDesc', models.TextField()),
                ('threadAuthor', models.CharField(max_length=50)),
                ('pubDate', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.IntegerField(default=1, max_length=1)),
                ('boardFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
            ],
        ),
    ]
