# Generated by Django 2.1.7 on 2019-03-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='isActive',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='thread',
            name='isActive',
            field=models.IntegerField(default=1),
        ),
    ]
