# Generated by Django 2.1.7 on 2019-03-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190326_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='boardImg',
            field=models.FilePathField(default='img/default.png'),
        ),
        migrations.AddField(
            model_name='thread',
            name='threadImg',
            field=models.FilePathField(default='img/default.png'),
        ),
    ]
