# Generated by Django 2.1.7 on 2019-03-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190327_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='threadAuthor',
            field=models.CharField(default='anon', max_length=50),
        ),
    ]
