# Generated by Django 2.1.7 on 2019-03-29 07:31

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20190328_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textMessage', models.TextField()),
                ('authorIP', models.CharField(max_length=200)),
                ('author', models.CharField(default='anon', max_length=50)),
                ('pubDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='thread',
            name='threadImg',
            field=models.FileField(default='img/default.png', storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='boards/static/boards'), upload_to='img/uploads/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='threadmessages',
            name='threadFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Thread'),
        ),
    ]
