# Generated by Django 2.1.7 on 2019-04-02 05:49

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20190329_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='boardImg',
            field=models.FileField(default='img/default.png', storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='boards/static/boards'), upload_to='img/uploads/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
