# Generated by Django 2.1.7 on 2019-04-02 11:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20190402_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='boardImg',
            field=models.ImageField(default='img/default.png', storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='boards/static/boards'), upload_to='img/uploads/%Y/%m'),
        ),
    ]
